# Actuator Health Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Custom Ping Details
management.info.env.enabled=true
info.app.name=Shortlink Service
info.app.description=URL Shortener API with Rate Limiting and QR Code support
info.app.version=0.0.1-SNAPSHOT
