spring.application.name=shortlink
spring.config.import=optional:classpath:actuator.properties

server.port=${PORT:8080}

spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/shortlink}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:local_postgres_pass}

# Dialect phải để tự động nhận diện hoặc cấu hình động
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
# spring.data.redis.password=
spring.data.redis.lettuce.pool.max-active=32
spring.data.redis.lettuce.pool.max-idle=16
spring.data.redis.lettuce.pool.max-wait=5000ms

# Rate Limit Configuration 
app.ratelimit.enabled=true
app.ratelimit.capacity=4000
app.ratelimit.tokens-per-minute=30000

# JWT Configuration
jwt.secret=${JWT_SECRET:t288U4Jl7qTlgQf57y6MIqgL3FnUpo5LR75HSWt+IAQ=}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Rate Limiting Configuration
app.ratelimit.capacity=${RATE_LIMIT_CAPACITY:100}
app.ratelimit.tokens-per-minute=${RATE_LIMIT_TPM:60}

# Snowflake Configuration
snowflake.worker-id=${SNOWFLAKE_WORKER_ID:1}
snowflake.datacenter-id=${SNOWFLAKE_DATACENTER_ID:1}
